- name: Installeer en configureer de Nginx Webserver
  hosts: webservers
  become: yes

  tasks:
    - name: 1. Zorg dat de server de nieuwste softwarelijsten heeft
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 2. Installeer het programma Nginx
      apt:
        name: nginx
        state: present

    - name: 3. Zorg dat Nginx aan staat en automatisch opstart na een reboot
      service:
        name: nginx
        state: started
        enabled: yes
