name: Deploy Demo API

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/external-api/app
            
            # Controleer of de map al een git repo is, zo niet: clone. Zo ja: pull.
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi
            
            npm install
            
            cd /opt/external-api
            sudo docker compose restart ext_nodejs
